"""File: core/sanitize.py
Purpose: Input sanitization utilities for user-supplied text content.

Gap 76: Headlines and captions generated by LLMs and editable by users
         must be sanitized before being persisted or sent to the frontend
         to prevent XSS injection through stored HTML.
"""

from __future__ import annotations

import html
import re

# Regex to strip all HTML/XML tags
_HTML_TAG_RE = re.compile(r"<[^>]+>", re.DOTALL)
# Regex to collapse multiple whitespace/newlines
_WHITESPACE_RE = re.compile(r"\s{2,}")


def sanitize_text(value: str, *, max_length: int = 500) -> str:
    """Strip HTML tags and escape entities from user-supplied text.

    Gap 76: Prevents XSS if LLM output or user edits contain HTML.
    This is intentionally destructive — tags are removed, not encoded,
    because captions/headlines should never contain HTML formatting.

    Args:
        value: Raw string input (e.g. LLM-generated headline).
        max_length: Truncate to this character limit (default 500).

    Returns:
        Sanitized plain-text string.
    """
    # 1. Unescape any double-encoded entities first
    value = html.unescape(value)
    # 2. Strip all HTML/XML tags
    value = _HTML_TAG_RE.sub("", value)
    # 3. Re-escape any remaining < > & " to their entities
    value = html.escape(value, quote=False)
    # 4. Collapse excessive whitespace
    value = _WHITESPACE_RE.sub(" ", value).strip()
    # 5. Enforce length cap
    return value[:max_length]


def sanitize_list(values: list[str], *, max_length: int = 500, max_items: int = 20) -> list[str]:
    """Sanitize a list of text values (e.g. hook_headlines).

    Args:
        values: List of raw strings.
        max_length: Per-item character limit.
        max_items: Maximum number of items to keep.

    Returns:
        Sanitized list.
    """
    return [sanitize_text(v, max_length=max_length) for v in values[:max_items]]
